#!/bin/bash

echo '# Autogenerated by (components/update.sh)' > ~/.config/i3/config
for i in  ~/.config/i3/config.d/*.conf; do
    cat "$i" >> ~/.config/i3/config
    echo -e "\n" >> ~/.config/i3/config
done